version: '3'

services:
  nginx:
    image: nginx:1.15-alpine
    depends_on:
    - flask_app
    ports:
    - "80:80"
    volumes:
      - ./data/nginx:/etc/nginx/conf.d

  flask_app:
    image: flask_app
    build:
      context: .
      dockerfile: ./Dockerfile
